repos:
  - repo: local
    hooks:
      - id: forbid-delete-markers
        name: Forbid DELETE_ME markers
        language: pygrep
        entry: \b(DELETE_ME|REMOVE_BEFORE_MERGE)\b
        types: [python]
        exclude: ^(logs/|docs/)

      - id: forbid-delete-blocks
        name: Forbid pending DELETE blocks
        language: pygrep
        entry: '^\s*#\s*region\s*DELETE_BLOCK:\s*start\b'
        types: [python]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
        language_version: python3.13

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: [--config=pyproject.toml, --fix]
        additional_dependencies: ["ruff==0.12.12"]
  
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.405   # use a current tag
    hooks:
      - id: pyright
        exclude: '(^tests/|.*/tests/|^test_.*\.py$|.*/test_.*\.py$)'
